carbon_project_rater:
  target: dev
  outputs:
    dev:
      type: postgres
      host: carbon-project-rater-db.cb6smiis4efz.eu-north-1.rds.amazonaws.com
      port: 5432
      user: postgres
      password: password
      dbname: carbon_project_rater
      schema: public
      threads: 4