"""Initial migration.

Revision ID: 5a42acdd43a8
Revises: 
Create Date: 2024-06-03 11:10:51.180173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a42acdd43a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_project',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('facility_name', sa.String(length=255), nullable=False),
        sa.Column('city', sa.String(length=255), nullable=True),
        sa.Column('state', sa.String(length=255), nullable=True),
        sa.Column('zip_code', sa.String(length=10), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('county', sa.String(length=255), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('industry_type', sa.String(length=255), nullable=True),
        sa.Column('total_mass_co2_sequestered', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2016', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2017', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2018', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2019', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2020', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2021', sa.Float(), nullable=True),
        sa.Column('total_mass_co2_sequestered_2022', sa.Float(), nullable=True),
        sa.Column('duration_years', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carbon_project')
    # ### end Alembic commands ###